### ISSUE TITLE
Add Valgrind analysis to test CI job

### ISSUE THREAD

**Issue by KyrietS** [KyrietS/trex#14]
**NOTE:** Valgrind is available only on Linux (sadpepe.png)

```yml
- name: apt install dependency
  run: |
    sudo apt-get -y install valgrind
    sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 

- name: Build tests
  run: |
    cmake -S tests -B build_tests -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    cmake --build build_tests --config ${{ matrix.build_type }}

- name: Run Valgrind
  run: valgrind ./build_tests/trex_tests
```
